
# cargo-vet audits file

[[audits.thread_local]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "1.1.4 -> 1.1.9"

[[audits.tracing-attributes]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-run"
delta = "0.1.28 -> 0.1.30"

[[audits.tracing-core]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "0.1.33 -> 0.1.34"

[[audits.tracing-log]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "0.1.3 -> 0.2.0"
notes = "Mostly just removes code."

[[audits.valuable]]
who = "Sebastian Wiesner <sebastian@swsnr.de>"
criteria = "safe-to-deploy"
delta = "0.1.0 -> 0.1.1"

[[trusted.alpm]]
criteria = "safe-to-run"
user-id = 37641 # Lulu (Morganamilo)
start = "2019-08-24"
end = "2026-10-03"

[[trusted.alpm-sys]]
criteria = "safe-to-run"
user-id = 37641 # Lulu (Morganamilo)
start = "2020-08-07"
end = "2026-10-03"

[[trusted.quote]]
criteria = "safe-to-run"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-09"
end = "2026-10-03"

[[trusted.serde]]
criteria = "safe-to-run"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2026-10-03"

[[trusted.serde_core]]
criteria = "safe-to-run"
user-id = 3618 # David Tolnay (dtolnay)
start = "2025-09-13"
end = "2026-10-03"

[[trusted.serde_derive]]
criteria = "safe-to-run"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2026-10-03"

[[trusted.syn]]
criteria = "safe-to-run"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2026-10-03"

[[trusted.unicode-ident]]
criteria = "safe-to-run"
user-id = 3618 # David Tolnay (dtolnay)
start = "2021-10-02"
end = "2026-10-03"

[[trusted.windows-sys]]
criteria = "safe-to-run"
user-id = 64539
start = "2021-11-15"
end = "2026-10-03"

[[trusted.windows-targets]]
criteria = "safe-to-run"
user-id = 64539
start = "2022-09-09"
end = "2026-10-03"

[[trusted.windows_aarch64_gnullvm]]
criteria = "safe-to-run"
user-id = 64539
start = "2022-09-01"
end = "2026-10-03"

[[trusted.windows_aarch64_msvc]]
criteria = "safe-to-run"
user-id = 64539
start = "2021-11-05"
end = "2026-10-03"

[[trusted.windows_i686_gnu]]
criteria = "safe-to-run"
user-id = 64539
start = "2021-10-28"
end = "2026-10-03"

[[trusted.windows_i686_gnullvm]]
criteria = "safe-to-run"
user-id = 64539
start = "2024-04-02"
end = "2026-10-03"

[[trusted.windows_i686_msvc]]
criteria = "safe-to-run"
user-id = 64539
start = "2021-10-27"
end = "2026-10-03"

[[trusted.windows_x86_64_gnu]]
criteria = "safe-to-run"
user-id = 64539
start = "2021-10-28"
end = "2026-10-03"

[[trusted.windows_x86_64_gnullvm]]
criteria = "safe-to-run"
user-id = 64539
start = "2022-09-01"
end = "2026-10-03"

[[trusted.windows_x86_64_msvc]]
criteria = "safe-to-run"
user-id = 64539
start = "2021-10-27"
end = "2026-10-03"
